#!/usr/bin/env bash

set -o errexit
set -o pipefail
if [[ ${DEBUG:-false} == "true" ]]; then
    set -o xtrace
fi

usage() {
cat <<EOF
  Usage: $0 --inventory_path INVENTORY_PATH --key_file KEY_FILE [--playbook PLAYBOOK] [--extra_args EXTRA_ARGS]
EOF
    exit 1
}

# parse arguments
while [[ $# -gt 0 ]]; do
    case $1 in
        --inventory_path)
            INVENTORY_PATH="$2" && shift 2 ;;
        --key_file)
            KEY_FILE="$2" && shift 2 ;;
        --playbook)
            PLAYBOOK="$2" && shift 2 ;;
        --extra_args)
            EXTRA_ARGS="$2" && shift 2 ;;
        *)
            echo "Unknown option: $1"
            usage ;;
    esac
done

[ "$INVENTORY_PATH" ] || usage
[ "$KEY_FILE" ] || usage
[ "$PLAYBOOK" ] || PLAYBOOK="playbooks/playbook.yml"
[ "$EXTRA_ARGS" ] || EXTRA_ARGS="--flush-cache --verbose"


# Decrypt deploy key
ansible-vault view --vault-id gitops@$PWD/vault ansible.b64 | base64 --decode > $KEY_FILE
chmod 0600 $KEY_FILE

# Add key to ssh-agent
eval $(ssh-agent)
ssh-add $KEY_FILE

#
# ansible -i $INVENTORY_PATH --key-file $KEY_FILE -m ping all 

ansible-playbook -i $INVENTORY_PATH --key-file $KEY_FILE $PLAYBOOK $EXTRA_ARGS

