#!/usr/bin/env bash

if [ -n "$1" ] ; then
    PWFILE="$1"
else
    DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"
    PWFILE=${VAULT_PASS_FILE:-"${DIR}/.vault.asc"}
fi

if [ -f "${PWFILE}" ]; then
    gpg --quiet --batch --use-agent --decrypt "${PWFILE}"
else
    echo "Password file not found: ${PWFILE}"
    help
    exit 1
fi
